### ISSUE TITLE
How to use these configs

### ISSUE THREAD

**Issue by narendra-kumawat** [TxGVNN/i3-config#3]
Configs are copied in ~/.i3 and i3 is reloaded but there is no effect or change

**Comment by gorkemerdogann** [comment]
After I cloned the repo to `~/.i3`, I copied files to `~/.config/i3/`.  It's worked. (raspbian buster)

**Comment by TxGVNN** [comment]
Hi @narendra-kumawat, sorry for replying too late.
And thank @gorkemerdogann for your good support.

The i3 provide many directories you can use. From `man i3`
```
   ~/.i3/config (or ~/.config/i3/config)
       When starting, i3 looks for configuration files in the following order:

        1. ~/.config/i3/config (or $XDG_CONFIG_HOME/i3/config if set)

        2. ~/.i3/config

        3. /etc/xdg/i3/config (or $XDG_CONFIG_DIRS/i3/config if  set)
        
        4. /etc/i3/config
```
Perhaps I should update README.md to recommend  everyone setup i3 into `~/.config/i3`
Thanks
