### ISSUE TITLE
Battery always shows 0

### ISSUE THREAD

**Issue by andrew-bydlon** [TxGVNN/i3-config#4]
On my 2 desktops and laptop, the battery status is always 0.  I'm running arch linux.

**Comment by TxGVNN** [comment]
Hello,

About battery percent, I'm using variable from conky. `${battery_percent}`
https://github.com/txgvnn/i3-config/blob/1e9635883c0a73c5f97f2121456ac973536d1d43/conky-bar#L94

If it is not correct in your case, you should write a script to print the battery percent from `acpi  -i`

You can see a example about audio here https://github.com/txgvnn/i3-config/blob/1e9635883c0a73c5f97f2121456ac973536d1d43/conky-bar#L90
