### ISSUE TITLE
use emacs register in x-register

### ISSUE THREAD

**Issue by QiangF** [TxGVNN/i3-config#5]
I was looking for a emacs register like feature too, and I found yours. Maybe just use emacs registers instead of these tmp files will give the user a consistent registers inside and outside emacs, eg. use emacsclient to access the register content.
Just an idea.

**Comment by QiangF** [comment]
You can use Shift+Insert  to make the paste more robust
https://github.com/zachcurry/emacs-anywhere/pull/66

**Comment by TxGVNN** [comment]
Oh, That is impressive. I don't know https://github.com/zachcurry/emacs-anywhere/pull/66

About tmp files, I want this configure doesn't depend on emacs. That why I don't use emacs registers.

Thank you very much!

**Comment by QiangF** [comment]
I modified the rofi based version a little bit, rofi looks much better than i3-input

    show_existing_registers () {
        # let's hope that nobody's LOGNAME contains ';'
        find "/tmp/" -maxdepth 1 -type f -name ".${LOGNAME}_x-register_*" |
        sed 's;'"/tmp/.${LOGNAME}_x-register_"';;' | sed ':a;N;s/\n/ /;ba'
    }

    if [ "$1" = "copy" ]; then
        register=$(echo | rofi -dmenu -p 'Copy to register' -mesg "Used: $(show_existing_registers)")
        # xsel -o > "/tmp/.${LOGNAME}_x-register_$register"
        xclip -o > "/tmp/.${LOGNAME}_x-register_$register"
    else
        register=$(show_existing_registers | rofi -dmenu -p 'Insert register: ')
        # could also check whether the register we picked exists
        cat "/tmp/.${LOGNAME}_x-register_$register" |
        # xsel -i -b && xdotool key --clearmodifiers Shift+Insert
        xclip -selection clipboard && xdotool key --clearmodifiers Shift+Insert
    fi

**Comment by TxGVNN** [comment]
Yeah! it looks like `selectrum/ivy/helm` ecosystem in Emacs. I don't use `rofi`, ya I still use dmenu may provide the same feature.

As I saw this guy do the version of youtube player https://github.com/sayan01/scripts/blob/master/yt by rofi/dmenu. So cool, I wonder should I switch to use `rofi/demu` instead of the default.

But as Emacs default. I want to provide a good default, then anyone can customize better as you're doing.

One more thing, May you change `xclip -selection clipboard` -> `xclip -i` as https://github.com/TxGVNN/i3-config/commit/ce4debeddfe8b799e7180ad2baa4f50746979363? Because I see `xclip -selection clipboard` doesn't work on some cases, I tested.

**Comment by QiangF** [comment]
I have improved the rofi edition to show both the register and the first line in it

    register_dir="/tmp/.${LOGNAME}_x-register/"

    [ -d $register_dir ] || mkdir $register_dir

    print_register_list () {
        ls "$register_dir" | tr "\n" " "
    }

    print_register_contents () {
        result=""
        for f in $(print_register_list); do
            temp_str=$(head -n1 -q "$register_dir$f" | tr "\n" " ")
            result+=$(printf '%s %s\n' "$f" "$temp_str")$'\\n'
        done
        echo -e $result
    }

    if [ "$1" = "copy" ]; then
        register=$(echo | rofi -dmenu -p 'Copy to register' -mesg "Used: $(print_register_list)")
        xclip -o > "$register_dir/$register"
    else
        register=$(print_register_contents | rofi -dmenu -p 'Insert register')
        cat "$register_dir/${register:0:1}" | xclip -selection clipboard && xdotool key --clearmodifiers Shift+Insert
    fi
